FROM ubuntu:16.04
RUN apt-get remove apt-xapian-index -y && \
autoclean -y && \
apt-get -y update && \
apt-get upgrade -y && \
apt-get install software-properties-common && \
apt-add-repository ppa:ansible/ansible && \
apt-get update && \
apt-get install ansible

CMD /bin/bash
