FROM ubuntu:16.04
RUN \
#apt-get remove apt-xapian-index -y && \
#autoclean -y && \
apt-get update && \
apt-get upgrade -y && \
apt-get install software-properties-common -y && \
apt-add-repository ppa:ansible/ansible && \
apt-get update && \
apt-get install ansible -y

CMD /bin/bash
