FROM ubuntu
#RUN apt-get remove apt-xapian-index -y && autoclean -y && \
RUN apt-get -y update && \
apt-get upgrade -y && \
apt-get install software-properties-common -y && \
apt-add-repository ppa:ansible/ansible && \
apt-get update && \
apt-get install ansible -y
CMD /bin/bash